global:
  scrape_interval: 15s

scrape_configs:
  - job_name: ingestion-api
    static_configs:
      - targets: ['ingestion-api:8080']

  - job_name: analytics-api
    static_configs:
      - targets: ['analytics-api:8080']

  - job_name: worker
    static_configs:
      - targets: ['worker:9091']